import type { CountryRow } from '@/app/countries/CountryEditModal';
import { REGIONS_BY_COUNTRY } from '@/constants/countryRegions.constants';
import { COUNTRIES, COUNTRIES_WITH_CODES } from '@/lib/news/countries';

const COUNTRY_CODE_MAP = Object.fromEntries(
  COUNTRIES_WITH_CODES.map(({ name, id }) => [name, id]),
) as Record<string, string>;

const CONTINENT_BY_ISO: Record<string, string> = {
  AF: 'West Asia',
  AL: 'East Europe',
  DZ: 'North Africa',
  AD: 'West Europe',
  AO: 'North Africa',
  AR: 'South America',
  AM: 'East Europe',
  AU: 'Oceania',
  AT: 'West Europe',
  AZ: 'East Asia',
  BS: 'Caribbean',
  BH: 'West Asia',
  BD: 'South Asia',
  BB: 'Caribbean',
  BY: 'East Europe',
  BE: 'West Europe',
  BZ: 'Central America',
  BJ: 'North Africa',
  BT: 'South Asia',
  BO: 'South America',
  BA: 'East Europe',
  BW: 'North Africa',
  BR: 'South America',
  BN: 'East Asia',
  BG: 'East Europe',
  BF: 'North Africa',
  BI: 'North Africa',
  KH: 'East Asia',
  CM: 'North Africa',
  CA: 'North America',
  CV: 'North Africa',
  CF: 'North Africa',
  TD: 'North Africa',
  CL: 'South America',
  CN: 'East Asia',
  CO: 'South America',
  KM: 'North Africa',
  CG: 'North Africa',
  CR: 'Central America',
  HR: 'East Europe',
  CU: 'Caribbean',
  CY: 'West Asia',
  CZ: 'East Europe',
  DK: 'West Europe',
  DJ: 'North Africa',
  DM: 'Caribbean',
  DO: 'Caribbean',
  EC: 'South America',
  EG: 'North Africa',
  SV: 'Central America',
  GQ: 'North Africa',
  ER: 'North Africa',
  EE: 'East Europe',
  ET: 'North Africa',
  FJ: 'Oceania',
  FI: 'West Europe',
  FR: 'West Europe',
  GA: 'North Africa',
  GM: 'North Africa',
  GE: 'East Europe',
  DE: 'West Europe',
  GH: 'North Africa',
  GR: 'East Europe',
  GD: 'Caribbean',
  GT: 'Central America',
  GN: 'North Africa',
  GW: 'North Africa',
  GY: 'South America',
  HT: 'Caribbean',
  HN: 'Central America',
  HU: 'East Europe',
  IS: 'West Europe',
  IN: 'South Asia',
  ID: 'East Asia',
  IR: 'West Asia',
  IQ: 'West Asia',
  IE: 'West Europe',
  IL: 'West Asia',
  IT: 'West Europe',
  JM: 'Caribbean',
  JP: 'East Asia',
  JO: 'West Asia',
  KZ: 'East Asia',
  KE: 'North Africa',
  KI: 'Oceania',
  KP: 'East Asia',
  KR: 'East Asia',
  XK: 'East Europe',
  KW: 'West Asia',
  KG: 'East Asia',
  LA: 'East Asia',
  LV: 'East Europe',
  LB: 'West Asia',
  LS: 'North Africa',
  LR: 'North Africa',
  LY: 'North Africa',
  LI: 'West Europe',
  LT: 'East Europe',
  LU: 'West Europe',
  MG: 'North Africa',
  MW: 'North Africa',
  MY: 'East Asia',
  MV: 'South Asia',
  ML: 'North Africa',
  MT: 'West Europe',
  MH: 'Oceania',
  MR: 'North Africa',
  MU: 'North Africa',
  MX: 'North America',
  FM: 'Oceania',
  MD: 'East Europe',
  MC: 'West Europe',
  MN: 'East Asia',
  ME: 'East Europe',
  MA: 'North Africa',
  MZ: 'North Africa',
  MM: 'East Asia',
  NA: 'North Africa',
  NR: 'Oceania',
  NP: 'South Asia',
  NL: 'West Europe',
  NZ: 'Oceania',
  NI: 'Central America',
  NE: 'North Africa',
  NG: 'North Africa',
  NO: 'West Europe',
  OM: 'West Asia',
  PK: 'South Asia',
  PW: 'Oceania',
  PS: 'West Asia',
  PA: 'Central America',
  PG: 'Oceania',
  PY: 'South America',
  PE: 'South America',
  PH: 'East Asia',
  PL: 'East Europe',
  PT: 'West Europe',
  QA: 'West Asia',
  RO: 'East Europe',
  RU: 'East Europe',
  RW: 'North Africa',
  KN: 'Caribbean',
  LC: 'Caribbean',
  VC: 'Caribbean',
  WS: 'Oceania',
  SM: 'West Europe',
  ST: 'North Africa',
  SA: 'West Asia',
  SN: 'North Africa',
  RS: 'East Europe',
  SC: 'North Africa',
  SL: 'North Africa',
  SG: 'East Asia',
  SK: 'East Europe',
  SI: 'East Europe',
  SB: 'Oceania',
  SO: 'North Africa',
  ZA: 'North Africa',
  SS: 'North Africa',
  ES: 'West Europe',
  LK: 'South Asia',
  SD: 'North Africa',
  SR: 'South America',
  SZ: 'North Africa',
  SE: 'West Europe',
  CH: 'West Europe',
  SY: 'West Asia',
  TW: 'East Asia',
  TJ: 'East Asia',
  TZ: 'North Africa',
  TH: 'East Asia',
  TL: 'East Asia',
  TG: 'North Africa',
  TO: 'Oceania',
  TT: 'Caribbean',
  TN: 'North Africa',
  TR: 'West Asia',
  TM: 'East Asia',
  TV: 'Oceania',
  UG: 'North Africa',
  UA: 'East Europe',
  AE: 'West Asia',
  GB: 'West Europe',
  US: 'North America',
  UY: 'South America',
  UZ: 'East Asia',
  VU: 'Oceania',
  VA: 'West Europe',
  VE: 'South America',
  VN: 'East Asia',
  YE: 'West Asia',
  ZM: 'North Africa',
  ZW: 'North Africa',
};

const CURRENCY_BY_ISO: Record<string, string> = {
  AF: 'AFN',
  AL: 'ALL',
  DZ: 'DZD',
  AD: 'EUR',
  AO: 'AOA',
  AR: 'ARS',
  AM: 'AMD',
  AU: 'AUD',
  AT: 'EUR',
  AZ: 'AZN',
  BS: 'BSD',
  BH: 'BHD',
  BD: 'BDT',
  BB: 'BBD',
  BY: 'BYN',
  BE: 'EUR',
  BZ: 'BZD',
  BJ: 'XOF',
  BT: 'BTN',
  BO: 'BOB',
  BA: 'BAM',
  BW: 'BWP',
  BR: 'BRL',
  BN: 'BND',
  BG: 'BGN',
  BF: 'XOF',
  BI: 'BIF',
  KH: 'KHR',
  CM: 'XAF',
  CA: 'CAD',
  CV: 'CVE',
  CF: 'XAF',
  TD: 'XAF',
  CL: 'CLP',
  CN: 'CNY',
  CO: 'COP',
  KM: 'KMF',
  CG: 'XAF',
  CR: 'CRC',
  HR: 'EUR',
  CU: 'CUP',
  CY: 'EUR',
  CZ: 'CZK',
  DK: 'DKK',
  DJ: 'DJF',
  DM: 'XCD',
  DO: 'DOP',
  EC: 'USD',
  EG: 'EGP',
  SV: 'USD',
  GQ: 'XAF',
  ER: 'ERN',
  EE: 'EUR',
  ET: 'ETB',
  FJ: 'FJD',
  FI: 'EUR',
  FR: 'EUR',
  GA: 'XAF',
  GM: 'GMD',
  GE: 'GEL',
  DE: 'EUR',
  GH: 'GHS',
  GR: 'EUR',
  GD: 'XCD',
  GT: 'GTQ',
  GN: 'GNF',
  GW: 'XOF',
  GY: 'GYD',
  HT: 'HTG',
  HN: 'HNL',
  HU: 'HUF',
  IS: 'ISK',
  IN: 'INR',
  ID: 'IDR',
  IR: 'IRR',
  IQ: 'IQD',
  IE: 'EUR',
  IL: 'ILS',
  IT: 'EUR',
  JM: 'JMD',
  JP: 'JPY',
  JO: 'JOD',
  KZ: 'KZT',
  KE: 'KES',
  KI: 'AUD',
  KP: 'KPW',
  KR: 'KRW',
  XK: 'EUR',
  KW: 'KWD',
  KG: 'KGS',
  LA: 'LAK',
  LV: 'EUR',
  LB: 'LBP',
  LS: 'LSL',
  LR: 'LRD',
  LY: 'LYD',
  LI: 'CHF',
  LT: 'EUR',
  LU: 'EUR',
  MG: 'MGA',
  MW: 'MWK',
  MY: 'MYR',
  MV: 'MVR',
  ML: 'XOF',
  MT: 'EUR',
  MH: 'USD',
  MR: 'MRU',
  MU: 'MUR',
  MX: 'MXN',
  FM: 'USD',
  MD: 'MDL',
  MC: 'EUR',
  MN: 'MNT',
  ME: 'EUR',
  MA: 'MAD',
  MZ: 'MZN',
  MM: 'MMK',
  NA: 'NAD',
  NR: 'AUD',
  NP: 'NPR',
  NL: 'EUR',
  NZ: 'NZD',
  NI: 'NIO',
  NE: 'XOF',
  NG: 'NGN',
  NO: 'NOK',
  OM: 'OMR',
  PK: 'PKR',
  PW: 'USD',
  PS: 'ILS',
  PA: 'PAB',
  PG: 'PGK',
  PY: 'PYG',
  PE: 'PEN',
  PH: 'PHP',
  PL: 'PLN',
  PT: 'EUR',
  QA: 'QAR',
  RO: 'RON',
  RU: 'RUB',
  RW: 'RWF',
  KN: 'XCD',
  LC: 'XCD',
  VC: 'XCD',
  WS: 'WST',
  SM: 'EUR',
  ST: 'STN',
  SA: 'SAR',
  SN: 'XOF',
  RS: 'RSD',
  SC: 'SCR',
  SL: 'SLE',
  SG: 'SGD',
  SK: 'EUR',
  SI: 'EUR',
  SB: 'SBD',
  SO: 'SOS',
  ZA: 'ZAR',
  SS: 'SSP',
  ES: 'EUR',
  LK: 'LKR',
  SD: 'SDG',
  SR: 'SRD',
  SZ: 'SZL',
  SE: 'SEK',
  CH: 'CHF',
  SY: 'SYP',
  TW: 'TWD',
  TJ: 'TJS',
  TZ: 'TZS',
  TH: 'THB',
  TL: 'USD',
  TG: 'XOF',
  TO: 'TOP',
  TT: 'TTD',
  TN: 'TND',
  TR: 'TRY',
  TM: 'TMT',
  TV: 'AUD',
  UG: 'UGX',
  UA: 'UAH',
  AE: 'AED',
  GB: 'GBP',
  US: 'USD',
  UY: 'UYU',
  UZ: 'UZS',
  VU: 'VUV',
  VA: 'EUR',
  VE: 'VES',
  VN: 'VND',
  YE: 'YER',
  ZM: 'ZMW',
  ZW: 'ZWL',
};

const OFFICIAL_LANGUAGE_BY_ISO: Record<string, string> = {
  AF: 'Pashto',
  AL: 'Albanian',
  DZ: 'Arabic',
  AD: 'Catalan',
  AO: 'Portuguese',
  AR: 'Spanish',
  AM: 'Armenian',
  AU: 'English',
  AT: 'German',
  AZ: 'Azerbaijani',
  BS: 'English',
  BH: 'Arabic',
  BD: 'Bengali',
  BB: 'English',
  BY: 'Belarusian',
  BE: 'Dutch',
  BZ: 'English',
  BJ: 'French',
  BT: 'Dzongkha',
  BO: 'Spanish',
  BA: 'Bosnian',
  BW: 'English',
  BR: 'Portuguese',
  BN: 'Malay',
  BG: 'Bulgarian',
  BF: 'French',
  BI: 'Kirundi',
  KH: 'Khmer',
  CM: 'French',
  CA: 'English',
  CV: 'Portuguese',
  CF: 'French',
  TD: 'French',
  CL: 'Spanish',
  CN: 'Chinese',
  CO: 'Spanish',
  KM: 'Arabic',
  CG: 'French',
  CR: 'Spanish',
  HR: 'Croatian',
  CU: 'Spanish',
  CY: 'Greek',
  CZ: 'Czech',
  DK: 'Danish',
  DJ: 'French',
  DM: 'English',
  DO: 'Spanish',
  EC: 'Spanish',
  EG: 'Arabic',
  SV: 'Spanish',
  GQ: 'Spanish',
  ER: 'Tigrinya',
  EE: 'Estonian',
  ET: 'Amharic',
  FJ: 'English',
  FI: 'Finnish',
  FR: 'French',
  GA: 'French',
  GM: 'English',
  GE: 'Georgian',
  DE: 'German',
  GH: 'English',
  GR: 'Greek',
  GD: 'English',
  GT: 'Spanish',
  GN: 'French',
  GW: 'Portuguese',
  GY: 'English',
  HT: 'French',
  HN: 'Spanish',
  HU: 'Hungarian',
  IS: 'Icelandic',
  IN: 'Hindi',
  ID: 'Indonesian',
  IR: 'Persian',
  IQ: 'Arabic',
  IE: 'English',
  IL: 'Hebrew',
  IT: 'Italian',
  JM: 'English',
  JP: 'Japanese',
  JO: 'Arabic',
  KZ: 'Kazakh',
  KE: 'English',
  KI: 'English',
  KP: 'Korean',
  KR: 'Korean',
  XK: 'Albanian',
  KW: 'Arabic',
  KG: 'Kyrgyz',
  LA: 'Lao',
  LV: 'Latvian',
  LB: 'Arabic',
  LS: 'English',
  LR: 'English',
  LY: 'Arabic',
  LI: 'German',
  LT: 'Lithuanian',
  LU: 'Luxembourgish',
  MG: 'Malagasy',
  MW: 'English',
  MY: 'Malay',
  MV: 'Dhivehi',
  ML: 'French',
  MT: 'Maltese',
  MH: 'English',
  MR: 'Arabic',
  MU: 'English',
  MX: 'Spanish',
  FM: 'English',
  MD: 'Romanian',
  MC: 'French',
  MN: 'Mongolian',
  ME: 'Montenegrin',
  MA: 'Arabic',
  MZ: 'Portuguese',
  MM: 'Burmese',
  NA: 'English',
  NR: 'English',
  NP: 'Nepali',
  NL: 'Dutch',
  NZ: 'English',
  NI: 'Spanish',
  NE: 'French',
  NG: 'English',
  NO: 'Norwegian',
  OM: 'Arabic',
  PK: 'Urdu',
  PW: 'English',
  PS: 'Arabic',
  PA: 'Spanish',
  PG: 'English',
  PY: 'Spanish',
  PE: 'Spanish',
  PH: 'Filipino',
  PL: 'Polish',
  PT: 'Portuguese',
  QA: 'Arabic',
  RO: 'Romanian',
  RU: 'Russian',
  RW: 'Kinyarwanda',
  KN: 'English',
  LC: 'English',
  VC: 'English',
  WS: 'Samoan',
  SM: 'Italian',
  ST: 'Portuguese',
  SA: 'Arabic',
  SN: 'French',
  RS: 'Serbian',
  SC: 'English',
  SL: 'English',
  SG: 'English',
  SK: 'Slovak',
  SI: 'Slovenian',
  SB: 'English',
  SO: 'Somali',
  ZA: 'English',
  SS: 'English',
  ES: 'Spanish',
  LK: 'Sinhala',
  SD: 'Arabic',
  SR: 'Dutch',
  SZ: 'English',
  SE: 'Swedish',
  CH: 'German',
  SY: 'Arabic',
  TW: 'Chinese',
  TJ: 'Tajik',
  TZ: 'Swahili',
  TH: 'Thai',
  TL: 'Portuguese',
  TG: 'French',
  TO: 'Tongan',
  TT: 'English',
  TN: 'Arabic',
  TR: 'Turkish',
  TM: 'Turkmen',
  TV: 'English',
  UG: 'English',
  UA: 'Ukrainian',
  AE: 'Arabic',
  GB: 'English',
  US: 'English',
  UY: 'Spanish',
  UZ: 'Uzbek',
  VU: 'English',
  VA: 'Italian',
  VE: 'Spanish',
  VN: 'Vietnamese',
  YE: 'Arabic',
  ZM: 'English',
  ZW: 'English',
};

const POPULATION_BY_ISO: Record<string, number> = {
  AF: 38042754,
  AL: 2845955,
  DZ: 43053054,
  AD: 79034,
  AO: 32866272,
  AR: 43432376,
  AM: 2963234,
  AU: 25499884,
  AT: 9006698,
  AZ: 10139177,
  BS: 393248,
  BH: 1701583,
  BD: 164689383,
  BB: 287371,
  BY: 9449323,
  BE: 11589623,
  BZ: 397628,
  BJ: 12123198,
  BT: 771612,
  BO: 11673021,
  BA: 3280819,
  BW: 2351627,
  BR: 212559417,
  BN: 437479,
  BG: 6948445,
  BF: 20903273,
  BI: 11890784,
  KH: 16718965,
  CM: 26545864,
  CA: 37742154,
  CV: 555988,
  CF: 4829767,
  TD: 16425859,
  CL: 19116201,
  CN: 1411750000,
  CO: 50882891,
  KM: 869601,
  CG: 5518092,
  CR: 5094118,
  HR: 4105267,
  CU: 11326616,
  CY: 1207359,
  CZ: 10708981,
  DK: 5831404,
  DJ: 988002,
  DM: 71986,
  DO: 10847910,
  EC: 17643054,
  EG: 102334404,
  SV: 6486205,
  GQ: 1402985,
  ER: 3455259,
  EE: 1326535,
  ET: 120283026,
  FJ: 896444,
  FI: 5540720,
  FR: 65273511,
  GA: 2225734,
  GM: 2416668,
  GE: 3720382,
  DE: 83166711,
  GH: 31072940,
  GR: 10423054,
  GD: 112519,
  GT: 17915568,
  GN: 13132792,
  GW: 1968001,
  GY: 786559,
  HT: 11402528,
  HN: 9904607,
  HU: 9660351,
  IS: 366425,
  IN: 1380004385,
  ID: 273523615,
  IR: 83992949,
  IQ: 40222503,
  IE: 4937786,
  IL: 8655541,
  IT: 60461826,
  JM: 2961167,
  JP: 125836021,
  JO: 10203134,
  KZ: 18776707,
  KE: 53771196,
  KI: 119446,
  KP: 25778809,
  KR: 51269185,
  XK: 1873160,
  KW: 4270571,
  KG: 6524195,
  LA: 7275560,
  LV: 1901548,
  LB: 6825445,
  LS: 2142249,
  LR: 5057681,
  LY: 6871292,
  LI: 38128,
  LT: 2795680,
  LU: 625978,
  MG: 27691018,
  MW: 19129952,
  MY: 32365999,
  MV: 540544,
  ML: 20250833,
  MT: 441543,
  MH: 59190,
  MR: 4649658,
  MU: 1265740,
  MX: 128932753,
  FM: 548914,
  MD: 4033963,
  MC: 39244,
  MN: 3278290,
  ME: 621718,
  MA: 36910560,
  MZ: 31255435,
  MM: 54409800,
  NA: 2540905,
  NR: 10882,
  NP: 29136808,
  NL: 17134872,
  NZ: 5084300,
  NI: 6624554,
  NE: 24211758,
  NG: 206139589,
  NO: 5421241,
  OM: 5106626,
  PK: 220892340,
  PW: 18092,
  PS: 5101414,
  PA: 4314767,
  PG: 8947024,
  PY: 7132538,
  PE: 32971854,
  PH: 109581078,
  PL: 37846611,
  PT: 10196709,
  QA: 2881053,
  RO: 19237691,
  RU: 145934462,
  RW: 12952218,
  KN: 53199,
  LC: 183629,
  VC: 110940,
  WS: 198414,
  SM: 33931,
  ST: 219159,
  SA: 34813871,
  SN: 16743927,
  RS: 8737371,
  SC: 98347,
  SL: 7976983,
  SG: 5850342,
  SK: 5458827,
  SI: 2078938,
  SB: 686878,
  SO: 15893222,
  ZA: 59308690,
  SS: 11193725,
  ES: 47351567,
  LK: 21413249,
  SD: 43849260,
  SR: 586634,
  SZ: 1160164,
  SE: 10099265,
  CH: 8654622,
  SY: 17500658,
  TW: 23816775,
  TJ: 9537645,
  TZ: 59734218,
  TH: 69799978,
  TL: 1318442,
  TG: 8278724,
  TO: 105697,
  TT: 1394973,
  TN: 11818619,
  TR: 84339067,
  TM: 6031200,
  TV: 11792,
  UG: 45741007,
  UA: 43733762,
  AE: 9890402,
  GB: 67886011,
  US: 331002651,
  UY: 3473727,
  UZ: 33469199,
  VU: 307145,
  VA: 825,
  VE: 28435943,
  VN: 97338579,
  YE: 29825964,
  ZM: 18383955,
  ZW: 14862924,
};

/** Preserves the original demo rows for countries that had hand-tuned values. */
const COUNTRY_ROW_OVERRIDES: Partial<Record<string, Omit<CountryRow, 'id' | 'name'>>> = {
  Afghanistan: {
    iso2: 'af',
    continent: 'West Asia',
    population: 38042754,
    officialLanguage: 'Afgano',
    primaryLanguage: 'English',
    secondaryLanguage: 'Hindi',
    eurRate: 91.35,
    usdRate: 77.2,
    currencyCode: 'AFN',
    regions: 33,
    settingCompleted: true,
  },
  Albania: {
    iso2: 'al',
    continent: 'West Europe',
    population: 2845955,
    officialLanguage: 'Albanian',
    primaryLanguage: 'English',
    secondaryLanguage: 'French',
    eurRate: 123.52,
    usdRate: 102.43,
    currencyCode: 'ALL',
    regions: 12,
  },
  Algeria: {
    iso2: 'dz',
    continent: 'North Africa',
    population: 43053054,
    officialLanguage: 'Arabic',
    primaryLanguage: 'Arabic',
    secondaryLanguage: 'French',
    eurRate: 158.87,
    usdRate: 132.91,
    currencyCode: 'DZD',
    regions: 48,
  },
  Argentina: {
    iso2: 'ar',
    continent: 'South America',
    population: 43432376,
    officialLanguage: 'Spanish',
    primaryLanguage: 'Spanish',
    secondaryLanguage: 'Italian',
    eurRate: 100.2,
    usdRate: 88.16,
    currencyCode: 'ARS',
    regions: 24,
  },
  Armenia: {
    iso2: 'am',
    continent: 'East Europe',
    population: 2963234,
    officialLanguage: 'Hayastan',
    primaryLanguage: 'Russian',
    secondaryLanguage: 'English',
    eurRate: 825.92,
    usdRate: 521.8,
    currencyCode: 'AMD',
    regions: 3,
  },
  Australia: {
    iso2: 'au',
    continent: 'Oceania',
    population: 25499884,
    officialLanguage: 'English',
    primaryLanguage: 'English',
    secondaryLanguage: '—',
    eurRate: 1.65,
    usdRate: 1.52,
    currencyCode: 'AUD',
    regions: 8,
  },
  Austria: {
    iso2: 'at',
    continent: 'West Europe',
    population: 9006698,
    officialLanguage: 'German',
    primaryLanguage: 'German',
    secondaryLanguage: 'English',
    eurRate: 1,
    usdRate: 1.08,
    currencyCode: 'EUR',
    regions: 9,
    settingCompleted: true,
  },
  Azerbaijan: {
    iso2: 'az',
    continent: 'East Asia',
    population: 10139177,
    officialLanguage: 'Azerbaijani',
    primaryLanguage: 'Russian',
    secondaryLanguage: 'English',
    eurRate: 2.08,
    usdRate: 1.85,
    currencyCode: 'AZN',
    regions: 10,
  },
  Bahamas: {
    iso2: 'bs',
    continent: 'North America',
    population: 393248,
    officialLanguage: 'English',
    primaryLanguage: 'English',
    secondaryLanguage: 'French',
    eurRate: 1.15,
    usdRate: 1,
    currencyCode: 'USD',
    regions: 15,
  },
  Bahrain: {
    iso2: 'bh',
    continent: 'West Asia',
    population: 1701583,
    officialLanguage: 'Arabic',
    primaryLanguage: 'English',
    secondaryLanguage: 'Urdu',
    eurRate: 0.42,
    usdRate: 0.38,
    currencyCode: 'BHD',
    regions: 4,
  },
  Bangladesh: {
    iso2: 'bd',
    continent: 'South Asia',
    population: 164689383,
    officialLanguage: 'Bengali',
    primaryLanguage: 'English',
    secondaryLanguage: 'Hindi',
    eurRate: 110.5,
    usdRate: 92.3,
    currencyCode: 'BDT',
    regions: 64,
  },
  Barbados: {
    iso2: 'bb',
    continent: 'Caribbean',
    population: 287371,
    officialLanguage: 'English',
    primaryLanguage: 'English',
    secondaryLanguage: 'French',
    eurRate: 2.4,
    usdRate: 2.0,
    currencyCode: 'BBD',
    regions: 11,
  },
};

function primaryLanguageFor(iso: string, officialLanguage: string): string {
  if (['US', 'GB', 'CA', 'AU', 'NZ', 'IE', 'IN', 'PK', 'BD', 'NG', 'KE', 'ZA', 'SG'].includes(iso)) {
    return 'English';
  }
  if (['FR', 'BE', 'CH', 'LU', 'MC', 'SN', 'ML', 'BF', 'NE', 'TG', 'BJ', 'CI'].includes(iso)) {
    return 'French';
  }
  if (
    ['DE', 'AT', 'LI'].includes(iso) ||
    ['German', 'Austrian'].some((l) => officialLanguage.includes(l))
  ) {
    return 'German';
  }
  if (
    ['ES', 'MX', 'AR', 'CO', 'CL', 'PE', 'VE', 'EC', 'BO', 'PY', 'UY', 'CR', 'PA', 'SV', 'GT', 'HN', 'NI', 'DO', 'CU'].includes(
      iso,
    )
  ) {
    return 'Spanish';
  }
  if (['BR', 'PT', 'AO', 'MZ', 'CV', 'ST', 'TL', 'GW'].includes(iso)) {
    return 'Portuguese';
  }
  if (['RU', 'BY', 'KZ', 'KG', 'UA'].includes(iso)) {
    return 'Russian';
  }
  if (['CN', 'TW'].includes(iso)) {
    return 'Chinese';
  }
  if (iso === 'JP') return 'Japanese';
  if (
    ['SA', 'EG', 'IQ', 'SY', 'JO', 'LB', 'KW', 'QA', 'BH', 'OM', 'YE', 'LY', 'TN', 'DZ', 'MA', 'SD', 'AE', 'PS'].includes(
      iso,
    )
  ) {
    return 'Arabic';
  }
  if (['IT', 'SM', 'VA'].includes(iso)) return 'Italian';
  return officialLanguage;
}

function secondaryLanguageFor(iso: string, primaryLanguage: string): string {
  if (primaryLanguage === 'English') {
    if (['IN', 'PK', 'BD'].includes(iso)) return 'Hindi';
    if (['BH', 'AE', 'QA', 'KW'].includes(iso)) return 'Urdu';
    return 'French';
  }
  if (primaryLanguage === 'French') return 'English';
  if (primaryLanguage === 'Spanish') {
    if (['AR', 'UY'].includes(iso)) return 'Italian';
    return 'English';
  }
  if (primaryLanguage === 'Arabic') return 'French';
  if (primaryLanguage === 'German') return 'English';
  if (primaryLanguage === 'Russian') return 'English';
  if (primaryLanguage === 'Chinese') return 'English';
  if (primaryLanguage === 'Portuguese') return 'English';
  return '—';
}

function regionCountFor(name: string): number {
  const regions = REGIONS_BY_COUNTRY[name];
  if (regions?.length) return regions.length;
  return 0;
}

function buildCountryRow(name: string, id: number): CountryRow {
  const override = COUNTRY_ROW_OVERRIDES[name];
  if (override) {
    return { id, name, ...override };
  }

  const iso = COUNTRY_CODE_MAP[name] ?? name.slice(0, 2).toUpperCase();
  const iso2 = iso.toLowerCase();
  const officialLanguage = OFFICIAL_LANGUAGE_BY_ISO[iso] ?? name;
  const primaryLanguage = primaryLanguageFor(iso, officialLanguage);
  const secondaryLanguage = secondaryLanguageFor(iso, primaryLanguage);
  const currencyCode = CURRENCY_BY_ISO[iso] ?? 'USD';
  const eurUsesEuro = currencyCode === 'EUR';

  return {
    id,
    name,
    iso2,
    continent: CONTINENT_BY_ISO[iso] ?? 'West Europe',
    population: POPULATION_BY_ISO[iso] ?? 0,
    officialLanguage,
    primaryLanguage,
    secondaryLanguage,
    eurRate: eurUsesEuro ? 1 : 1.08,
    usdRate: currencyCode === 'USD' ? 1 : 1.08,
    currencyCode,
    regions: regionCountFor(name),
  };
}

export const COUNTRIES_DASHBOARD_ROWS: CountryRow[] = COUNTRIES.map((name, index) =>
  buildCountryRow(name, index + 1),
);

export const COUNTRIES_PAGE_SIZE = 20;
